-
  name: 'overview'
  uriPattern: ''
  defaults:
    '@package':    'Mk.Vote'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true
  
##
# Route to to a ranking list
-
  name: 'ranking list'
#  uriPattern: '{@package}/{rankingList}/{@action}'
  uriPattern: '{rankingList}/{@action}'
  
  defaults:
    '@package':    'Mk.Vote'
    '@controller': 'RankingList'
    '@action':     'show'
    '@format':     'html'
#  appendExceedingArguments: true
  routeParts:
    rankingList:
      objectType: 'Mk\Vote\Domain\Model\RankingList'
      uriPattern: '{name}'
