#                                                                        #
# Settings Configuration for the Vote package                            #
#                                                                        #


Mk:
  Vote:
    numberOfPartiesForPercentageForm: 7